version: 2.1

#orbs:
#  win: circleci/windows@1.0.0

commands:
  test_command:
    parameters:
      gcc_version:
        type: integer
        default: 8
    steps:
      - run:
          name: "Test command"
          command: |
            echo "Test command"
            echo "gcc version 0: $(gcc -v)"
            echo ""
            echo "gcc version 02: $(g++ -v)"
            echo "Param: g++-<< parameters.gcc_version >>"
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt update
            sudo apt remove g++-5 gcc-5
            if [ << parameters.gcc_version >> == 9 ]; then
            sudo apt install -y g++-9
              sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 --slave /usr/bin/g++ g++ /usr/bin/g++-9
            elif [ << parameters.gcc_version >> == 8 ]; then
              sudo apt install -y g++-8
                sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-8
            else
              echo "wrong gcc version"
            exit 1
            fi
            echo "gcc version 1: $(gcc -v)"
            echo ""
            echo "gcc version 2: $(g++ -v)"
          shell: /bin/bash

jobs:
  test_1:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Test job"
          command: |
            echo "Call test_command"
          shell: /bin/bash
      - test_command:
          gcc_version: 7

workflows:
  version: 2
  test_workspace:
    jobs:
      - test_1
