version: 2.1

#orbs:
#  win: circleci/windows@1.0.0

jobs:
  save_data_1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Test 1"
      - restore_cache:
          key: -v1-test{{ arch }}-{{ .Revision }}
      - run:
          name: Build Voice CPP slave
          command: |
            echo "currenr dir: $(pwd)"
            cd ~
            echo "currenr dir-new: $(pwd)"
            mkdir -p test_dir
            echo "test-1" > test_dir/test_file.txt
          shell: /bin/bash
      - save_cache:
          key: -v1-test{{ arch }}-{{ .Revision }}
          paths:
            - "~/test_dir"
  save_data_2:
    docker:
      - image: circleci/redis:5.0.0-32bit
    steps:
      - checkout
      - run: echo "Test 2"
      - restore_cache:
          key: -v1-test{{ arch }}-{{ .Revision }}
      - run:
          name: Build Voice CPP slave
          command: |
            echo "currenr dir: $(pwd)"
            cd ~
            echo "currenr dir-new: $(pwd)"
            mkdir -p test_dir
            echo "test-2" > test_dir/test_file.txt
          shell: /bin/bash
      - save_cache:
          key: -v1-test{{ arch }}-{{ .Revision }}
          paths:
            - "~/test_dir"
  save_data_3:
    docker:
      - image: circleci/php:7.3.6
    steps:
      - checkout
      - run: echo "Test 3"
      - restore_cache:
          key: -v1-test{{ arch }}-{{ .Revision }}
      - run:
          name: Build Voice CPP slave
          command: |
            echo "currenr dir: $(pwd)"
            cd ~
            echo "currenr dir-new: $(pwd)"
            mkdir -p test_dir
            echo "test-3" > test_dir/test_file.txt
          shell: /bin/bash
      - save_cache:
          key: -v1-test{{ arch }}-{{ .Revision }}
          paths:
            - "~/test_dir"
  check_data_1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - restore_cache:
          key: -v1-test{{ arch }}-{{ .Revision }}
      - run: echo "Test cache"
      - save_cache:
          key: -v1-test{{ arch }}-{{ .Revision }}
          paths:
            - "~/test_dir"
      - run:
          name: Check workspace attached
          command: |
            echo "currenr dir: $(pwd)"
            cd ~
            echo "currenr dir-new: $(pwd)"
            cat test_dir/test_file.txt
            if [[ $? -eq 0 ]]; then
                echo "Workspace persisted";
            else
                echo "Workspace did not persist"; exit 1
            fi
  check_data_2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - restore_cache:
          key: -v1-test{{ arch }}-{{ .Revision }}
      - run: echo "Test cache"
      - save_cache:
          key: -v1-test{{ arch }}-{{ .Revision }}
          paths:
            - "~/test_dir"
      - run:
          name: Check workspace attached
          command: |
            echo "currenr dir: $(pwd)"
            cd ~
            echo "currenr dir-new: $(pwd)"
            cat test_dir/test_file.txt
            if [[ $? -eq 0 ]]; then
                echo "Workspace persisted";
            else
                echo "Workspace did not persist"; exit 1
            fi
  check_data_3:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - restore_cache:
          key: -v1-test{{ arch }}-{{ .Revision }}
      - run: echo "Test cache"
      - save_cache:
          key: -v1-test{{ arch }}-{{ .Revision }}
          paths:
            - "~/test_dir"
      - run:
          name: Check workspace attached
          command: |
            echo "currenr dir: $(pwd)"
            cd ~
            echo "currenr dir-new: $(pwd)"
            cat test_dir/test_file.txt
            if [[ $? -eq 0 ]]; then
                echo "Workspace persisted";
            else
                echo "Workspace did not persist"; exit 1
            fi
workflows:
  version: 2
  test_workspace:
    jobs:
      - save_data_1
      - save_data_2
      - save_data_3
      - check_data_1:
          requires:
            - save_data_1
      - check_data_2:
          requires:
            - save_data_2
      - check_data_3:
          requires:
            - save_data_3
