 version: 2
 jobs:
   test_one:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "CircleCI test 1"
       - run: mkdir -p my_workspace
       - run: echo "Trying out workspaces" > my_workspace/echo-output
       - persist_to_workspace:
           # Must be an absolute path, or relative path from working_directory
           root: my_workspace
           # Must be relative path from root
           paths:
             - echo-output
   test_two:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "CircleCI test 2"
       - attach_workspace:
           # Must be absolute path or relative path from working_directory
           at: my_workspace
       - run: |
           if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
             echo "Success!";
           else
             echo "Error!"; exit 1
           fi
 workflows:
   version: 2
   test_one_and_two:
     jobs:
       - test_one
       - test_two:
           requires:
             - test_one
