version: 2.1

aliases:
  - &workspace
      ~/main_dir

executors:
  macos-ios-executor-xcode11:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: *workspace

commands:
  test_command_1:
    description: Test command 1 description
    steps:
      - run:
          name: "Test command 1 run 1 name"
          command: |
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
            dateq
          shell: /bin/bash
      - next_test_step

  test_command_2:
    description: Test command 2 description
    steps:
      - run:
          name: "Test command 2"
          command: |
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
            dateq
      - next_test_step

  test_command_3:
    description: Test command 3 description
    steps:
      - run:
          name: "Test command 3"
          command: |
            set +e
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
            dateq
          shell: /bin/bash
      - next_test_step

  test_command_4:
    description: Test command 4 description
    steps:
      - run:
          name: "Test command 4"
          command: |
            set +e
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
            dateq
      - next_test_step

  test_command_5:
    description: Test command 5 description
    steps:
      - run:
          name: "Test command 5"
          command: |
            set -e
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
            dateq
          shell: /bin/bash
      - next_test_step

  test_command_6:
    description: Test command 6 description
    steps:
      - run:
          name: "Test command 6"
          command: |
            set -e
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
            dateq
      - next_test_step

  test_command_7:
    description: Test command 7 description
    steps:
      - run:
          name: "Test command 7"
          command: |
            set -eo pipefail
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
            dateq
          shell: /bin/bash
      - next_test_step

  test_command_8:
    description: Test command 8 description
    steps:
      - run:
          name: "Test command 8"
          command: |
            set -eo pipefail
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
            dateq
      - next_test_step

  test_command_9:
    description: Test command 9 description
    steps:
      - run:
          name: "Test command 1"
          command: |
            set +eo pipefail
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
            dateq
          shell: /bin/bash
      - next_test_step

  test_command_10:
    description: Test command 10 description
    steps:
      - run:
          name: "Test command 1"
          command: |
            set +eo pipefail
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
            dateq
      - next_test_step

  test_command_11:
    description: Test command 11 description
    steps:
      - run:
          name: "Test command 1"
          command: |
            set -o pipefail
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
            dateq
          shell: /bin/bash
      - next_test_step

  test_command_12:
    description: Test command 12 description
    steps:
      - run:
          name: "Test command 1"
          command: |
            set -o pipefail
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
            dateq
      - next_test_step

  test_command_13:
    description: Test command 13 description
    steps:
      - run:
          name: "Test command 1"
          command: |
            set +o pipefail
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
            dateq
          shell: /bin/bash
      - next_test_step

  test_command_14:
    description: Test command 14 description
    steps:
      - run:
          name: "Test command 1"
          command: |
            set +o pipefail
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
            dateq
      - next_test_step

  next_test_step:
    description: The next test step
    steps:
      - run:
          name: "The next test step"
          command: |
            echo "Next test step"
          when: always

jobs:
  test_1:
    executor: macos-ios-executor-xcode11
    steps:
      - run:
          name: "Test job 1 name"
          command: |
            echo "Test job 1"
          shell: /bin/bash
      - test_command_1

  test_2:
    executor: macos-ios-executor-xcode11
    steps:
      - run:
          name: "Test job 2 name"
          command: |
            echo "Test job 2"
          shell: /bin/bash
      - test_command_2

  test_3:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Test job 3 name"
          command: |
            echo "Test job 3"
          shell: /bin/bash
      - test_command_3

  test_4:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Test job 4 name"
          command: |
            echo "Test job 4"
          shell: /bin/bash
      - test_command_4

  test_5:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Test job 5 name"
          command: |
            echo "Test job 5"
          shell: /bin/bash
      - test_command_5

  test_6:
    executor: macos-ios-executor-xcode11
    steps:
      - run:
          name: "Test job 6 name"
          command: |
            echo "Test job 6"
          shell: /bin/bash
      - test_command_6

  test_7:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Test job 7 name"
          command: |
            echo "Test job 7"
          shell: /bin/bash
      - test_command_7

  test_8:
    executor: macos-ios-executor-xcode11
    steps:
      - run:
          name: "Test job 8"
          command: |
            echo "Test job 8"
          shell: /bin/bash
      - test_command_8

  test_9:
    executor: macos-ios-executor-xcode11
    steps:
      - run:
          name: "Test job 9"
          command: |
            echo "Test job 9"
          shell: /bin/bash
      - test_command_9

  test_10:
    executor: macos-ios-executor-xcode11
    steps:
      - run:
          name: "Test job 10"
          command: |
            echo "Test job 10"
          shell: /bin/bash
      - test_command_10

  test_11:
    executor: macos-ios-executor-xcode11
    steps:
      - run:
          name: "Test job 11"
          command: |
            echo "Test job 11"
          shell: /bin/bash
      - test_command_11

  test_12:
    executor: macos-ios-executor-xcode11
    steps:
      - run:
          name: "Test job 12"
          command: |
            echo "Test job 12"
          shell: /bin/bash
      - test_command_12

  test_13:
    executor: macos-ios-executor-xcode11
    steps:
      - run:
          name: "Test job 13"
          command: |
            echo "Test job 13"
          shell: /bin/bash
      - test_command_13

  test_14:
    executor: macos-ios-executor-xcode11
    steps:
      - run:
          name: "Test job 14"
          command: |
            echo "Test job 14"
          shell: /bin/bash
      - test_command_14

workflows:
  version: 2
  test_workflow:
    jobs:
      - test_1
      - test_2
#      - test_3
#      - test_4
#      - test_5
#      - test_6
#      - test_7
#      - test_8
#      - test_9
#      - test_10
#      - test_11
#      - test_12
#      - test_13
#      - test_14
