version: 2.1

commands:
  test_command_1:
    description: Test command 1 description
    steps:
      - run:
          name: "Test command 1 run 1 name"
          command: |
            echo 'export TEST_VAR="test_234"' >> $BASH_ENV
            echo "test var: $TEST_VAR"
          shell: /bin/bash
      - test_command_2

  test_command_2:
    description: Test command 2 description
    steps:
      - run:
          name: "Test command 2 name"
          command: |
            echo "test var no source: $TEST_VAR"
            source $BASH_ENV
            echo "test var with source: $TEST_VAR"
          shell: /bin/bash

  test_command_3:
    description: Test command 3 description
    steps:
      - run:
          name: "Test command 3 run 1 name"
          command: |
            echo 'export TEST_VAR_2="test_236"' >> $BASH_ENV
          shell: /bin/bash
      - test_command_4

  test_command_4:
    description: Test command 4 description
    steps:
      - run:
          name: "Test command 4 run 1 name"
          command: |
            echo "test var: $TEST_VAR_2"
          shell: /bin/bash
      - run:
          name: "Test command 4 run 2 name"
          command: |
            echo "test var: $TEST_VAR_2"
          shell: /bin/bash

jobs:
  test_1:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Test job 1 name"
          command: |
            echo "Test job 1"
          shell: /bin/bash
      - test_command_1

  test_2:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Test job 2 name"
          command: |
            echo "Test job 2"
          shell: /bin/bash
      - test_command_2

  test_3:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Test job 3 name"
          command: |
            echo "Test job 3"
          shell: /bin/bash
      - test_command_3

  test_4:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Test job 4 name"
          command: |
            echo "Test job 4"
          shell: /bin/bash
      - test_command_4

workflows:
  version: 2
  test_workflow:
    jobs:
      - test_1
      - test_3
