version: 2.1

aliases:
  - &workspace
      ~/main_dir

executors:
  macos-ios-executor-xcode11:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: *workspace

commands:
  test_command_1:
    description: Test command 1 description
    steps:
      - run:
          name: "Test command 1 run 1 name"
          command: |
            echo "one"
            dateq
            echo "two"
          shell: /bin/bash
      - run:
          name: "Test command 1 run 2"
          command: |
            echo "one"
            dateq
            echo "two"
      - run:
          name: "Test command 1 run 3"
          command: |
            set +e
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
          shell: /bin/bash
      - run:
          name: "Test command 1 run 4"
          command: |
            set +e
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
      - run:
          name: "Test command 1 run 5"
          command: |
            set -e
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
          shell: /bin/bash
      - run:
          name: "Test command 1 run 6"
          command: |
            set -e
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
      - run:
          name: "Test command 1 run 7"
          command: |
            set -eo pipefail
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
          shell: /bin/bash
      - run:
          name: "Test command 1 run 8"
          command: |
            set -eo pipefail
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
      - run:
          name: "Test command 1 run 9"
          command: |
            set +eo pipefail
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"
          shell: /bin/bash
      - run:
          name: "Test command 1 run 10"
          command: |
            set +eo pipefail
            echo "one"
            dateq
            echo "two"
            dateq
            echo "three"

  test_command_2:
    description: Test command 2 description
    steps:
      - run:
          name: "Test command 2 name"
          command: |
            echo "one"
            dateas
            echo "two"
          shell: /bin/bash

  test_command_3:
    description: Test command 3 description
    steps:
      - run:
          name: "Test command 3 run 1 name"
          command: |
            set -e
            echo "one"
            dateas
            echo "two"
          shell: /bin/bash

  test_command_4:
    description: Test command 4 description
    steps:
      - run:
          name: "Test command 4 run 1 name"
          command: |
            set -e
            echo "one"
            dateas
            echo "two"
            datfh
          shell: /bin/bash

  test_command_5:
    description: Test command 5 description
    steps:
      - run:
          name: "Test command 5 run 1 name"
          command: |
            set +e
            echo "one"
            dateas
            echo "two"
          shell: /bin/bash

  test_command_6:
    description: Test command 6 description
    steps:
      - run:
          name: "Test command 6 run 1 name"
          command: |
            set +e
            echo "one"
            dateas
            echo "two"
            datrhj
          shell: /bin/bash

  test_command_7:
    description: Test command 7 description
    steps:
      - run:
          name: "Test command 7 run 1 name"
          command: |
            set -eo pipefail
            echo "one"
            dateas
            echo "two"
          shell: /bin/bash

  test_command_8:
    description: Test command 5_1 description
    steps:
      - run:
          name: "Test command 5_1 run 1 name"
          command: |
            set -eo pipefail
            echo "one"
            dateas
            echo "two"
            datrhj
          shell: /bin/bash

jobs:
  test_1:
    executor: macos-ios-executor-xcode11
    steps:
      - run:
          name: "Test job 1 name"
          command: |
            echo "Test job 1"
          shell: /bin/bash
      - test_command_1

  test_2:
    executor: macos-ios-executor-xcode11
    steps:
      - run:
          name: "Test job 2 name"
          command: |
            echo "Test job 2"
          shell: /bin/bash
      - test_command_2

  test_3:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Test job 3 name"
          command: |
            echo "Test job 3"
          shell: /bin/bash
      - test_command_3

  test_4:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Test job 4 name"
          command: |
            echo "Test job 4"
          shell: /bin/bash
      - test_command_4

  test_5:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Test job 5 name"
          command: |
            echo "Test job 5"
          shell: /bin/bash
      - test_command_5

  test_6:
    executor: macos-ios-executor-xcode11
    steps:
      - run:
          name: "Test job 6 name"
          command: |
            echo "Test job 6"
          shell: /bin/bash
      - test_command_6

  test_7:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: "Test job 7 name"
          command: |
            echo "Test job 7"
          shell: /bin/bash
      - test_command_7

  test_8:
    executor: macos-ios-executor-xcode11
    steps:
      - run:
          name: "Test job 8"
          command: |
            echo "Test job 8_1"
          shell: /bin/bash
      - test_command_8

workflows:
  version: 2
  test_workflow:
    jobs:
      - test_1
      - test_2
      - test_3
      - test_4
      - test_5
      - test_6
      - test_7
      - test_8
