version: 2.1

#orbs:
#  win: circleci/windows@1.0.0

commands:
  test_command:
    parameters:
      test_param:
        type: string
        default: "default-1"
    steps:
      - run:
          name: "Test command"
          command: |
            echo "Test command"
            echo "Param: << parameters.test_param >>"
          shell: /bin/bash

jobs:
  test_1:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run:
          name: "Test job"
          command: |
            echo "Call test_command"
          shell: /bin/bash
      - test_command:
          test_param: "test-123"

workflows:
  version: 2
  test_workspace:
    jobs:
      - test_1
