version: 2
jobs:
  save_data_1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Test 1"
      - run:
          name: Build Voice CPP slave
          command: |
            echo "currenr dir: $(pwd)"
            mkdir -p test_dir
            echo "test-1" > test_dir/test_file.txt
          shell: /bin/bash
      - persist_to_workspace:
          root: ../
          paths: test_dir
  check_data:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - attach_workspace:
          at: test_dir
      - run:
          name: Check workspace attached
          command: |
            cat test_dir/test_file.txt
            if [[ $? -eq 0 ]]; then
                echo "Workspace persisted";
            else
                echo "Workspace did not persist"; exit 1
            fi
workflows:
  version: 2
  test_workspace:
    jobs:
      - save_data_1
      - check_data:
          requires:
            - save_data_1
